import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // 产品文档
  product: [
    {
      type: 'autogenerated',
      dirName: 'product',
    },
  ],

  // UI设计
  'ui-design': [
    {
      type: 'autogenerated',
      dirName: 'ui-design',
    },
  ],

  // 技术文档
  technical: [
    {
      type: 'autogenerated',
      dirName: 'technical',
    },
  ],

  // E2E测试用例
  e2e: [
    {
      type: 'autogenerated',
      dirName: 'e2e',
    },
  ],
};

export default sidebars;
