"""add_addresses_table_and_order_updates

Revision ID: 3729ce0bf52d
Revises: 005
Create Date: 2026-04-20 01:18:46.089396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3729ce0bf52d'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('recipient_name', sa.String(length=100), nullable=False))
    op.add_column('addresses', sa.Column('province', sa.String(length=50), nullable=False))
    op.add_column('addresses', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('addresses', sa.Column('district', sa.String(length=50), nullable=False))
    op.add_column('addresses', sa.Column('street', sa.String(length=200), nullable=False))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.drop_column('addresses', 'name')
    op.drop_column('addresses', 'address')
    op.add_column('cart_items', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.add_column('cart_items', sa.Column('sku_variant', sa.Text(), nullable=True))
    op.alter_column('cart_items', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_cart_items_session_id'), 'cart_items', ['session_id'], unique=False)
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('name'), table_name='categories')
    op.add_column('orders', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    op.alter_column('products', 'images',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products', 'sku_variants',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products', 'specifications',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('users', 'password_history',
               existing_type=mysql.JSON(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('phone'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', mysql.DATETIME(), nullable=True))
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'password_history',
               existing_type=sa.String(length=1000),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.alter_column('products', 'specifications',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('products', 'sku_variants',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('products', 'images',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_column('orders', 'address_id')
    op.drop_column('orders', 'session_id')
    op.create_index(op.f('name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_cart_items_session_id'), table_name='cart_items')
    op.alter_column('cart_items', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('cart_items', 'sku_variant')
    op.drop_column('cart_items', 'session_id')
    op.add_column('addresses', sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.add_column('addresses', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'street')
    op.drop_column('addresses', 'district')
    op.drop_column('addresses', 'city')
    op.drop_column('addresses', 'province')
    op.drop_column('addresses', 'recipient_name')
    # ### end Alembic commands ###
