"""Create users table

Revision ID: be51fba86296
Revises:
Create Date: 2026-05-26 18:45:13.453315

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be51fba86296"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)

    # Insert initial admin user
    # Password: abcd1234 (bcrypt hash)
    op.execute(
        """
        INSERT INTO users (phone, hashed_password, username, is_admin, is_active, created_at, updated_at)
        VALUES (
            '13800138000',
            '$2b$12$zNSI5rDETKkcC0Z6q8Y3IeEO8HWBfHpQCpgi0EN68jotvlhH6YAkW',
            '系统管理员',
            TRUE,
            TRUE,
            NOW(),
            NOW()
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
