"""create skills tables

Revision ID: e3168b84dc2d
Revises: 117dfc44c27a
Create Date: 2026-05-28 22:08:47.874975

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3168b84dc2d"
down_revision: Union[str, None] = "create_agent_prototype_tables"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("level", sa.Enum("PLANNING", "FUNCTIONAL", "ATOMIC", name="skilllevel"), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("create_user_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Enum("DRAFT", "ACTIVE", "DISABLED", name="skillstatus"), nullable=False),
        sa.Column("draft_snapshot", sa.JSON(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_skill_deleted_at", "skills", ["deleted_at"], unique=False)
    op.create_index("idx_skill_level", "skills", ["level"], unique=False)
    op.create_index("idx_skill_status", "skills", ["status"], unique=False)
    op.create_index(op.f("ix_skills_code"), "skills", ["code"], unique=True)
    op.create_index(op.f("ix_skills_create_user_id"), "skills", ["create_user_id"], unique=False)
    op.create_table(
        "file_metadata",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_file_name", "file_metadata", ["name"], unique=False)
    op.create_index(op.f("ix_file_metadata_path"), "file_metadata", ["path"], unique=True)
    op.create_index(op.f("ix_file_metadata_skill_id"), "file_metadata", ["skill_id"], unique=False)
    op.create_table(
        "skill_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("file_snapshot", sa.JSON(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_versions_skill_id"), "skill_versions", ["skill_id"], unique=False)
    op.create_index("uk_skill_version", "skill_versions", ["skill_id", "version"], unique=True)
    op.create_table(
        "files",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("file_metadata_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["file_metadata_id"], ["file_metadata.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_file_metadata_id"), "files", ["file_metadata_id"], unique=False)
    op.create_index("uk_file_metadata_version", "files", ["file_metadata_id", "version"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uk_file_metadata_version", table_name="files")
    op.drop_index(op.f("ix_files_file_metadata_id"), table_name="files")
    op.drop_table("files")
    op.drop_index("uk_skill_version", table_name="skill_versions")
    op.drop_index(op.f("ix_skill_versions_skill_id"), table_name="skill_versions")
    op.drop_table("skill_versions")
    op.drop_index(op.f("ix_file_metadata_skill_id"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_path"), table_name="file_metadata")
    op.drop_index("idx_file_name", table_name="file_metadata")
    op.drop_table("file_metadata")
    op.drop_index(op.f("ix_skills_create_user_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_code"), table_name="skills")
    op.drop_index("idx_skill_status", table_name="skills")
    op.drop_index("idx_skill_level", table_name="skills")
    op.drop_index("idx_skill_deleted_at", table_name="skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
