"""init_tables

Revision ID: c745fa6b261f
Revises: be51fba86296
Create Date: 2026-05-27 18:20:23.180657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c745fa6b261f'
down_revision: Union[str, None] = 'be51fba86296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('COMPANY', 'BRANCH', 'DEPARTMENT', 'SUB_DEPARTMENT', name='orgunittype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='orgunitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_unit_parent_level', 'organization_unit', ['parent_id', 'level'], unique=False)
    op.create_index('idx_org_unit_status', 'organization_unit', ['status'], unique=False)
    op.create_index(op.f('ix_organization_unit_code'), 'organization_unit', ['code'], unique=True)
    op.create_index(op.f('ix_organization_unit_parent_id'), 'organization_unit', ['parent_id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('primary_unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ONBOARDING', 'ON_JOB', 'TRANSFERRING', 'OFFBOARDING', name='employeestatus'), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('dimission_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_unit_id'], ['organization_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_deleted', 'employee', ['is_deleted'], unique=False)
    op.create_index('idx_employee_name', 'employee', ['name'], unique=False)
    op.create_index('idx_employee_status', 'employee', ['status'], unique=False)
    op.create_index('idx_employee_unit_status', 'employee', ['primary_unit_id', 'status'], unique=False)
    op.create_index(op.f('ix_employee_employee_no'), 'employee', ['employee_no'], unique=True)
    op.create_index(op.f('ix_employee_primary_unit_id'), 'employee', ['primary_unit_id'], unique=False)
    op.create_table('org_unit_closure',
    sa.Column('ancestor_id', sa.Integer(), nullable=False),
    sa.Column('descendant_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['organization_unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['organization_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id')
    )
    op.create_index('idx_closure_ancestor', 'org_unit_closure', ['ancestor_id'], unique=False)
    op.create_index('idx_closure_depth', 'org_unit_closure', ['depth'], unique=False)
    op.create_index('idx_closure_descendant', 'org_unit_closure', ['descendant_id'], unique=False)
    op.create_table('employee_secondary_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['organization_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'unit_id', name='uq_employee_unit')
    )
    op.create_index('idx_secondary_employee', 'employee_secondary_unit', ['employee_id'], unique=False)
    op.create_index('idx_secondary_unit', 'employee_secondary_unit', ['unit_id'], unique=False)
    op.create_table('employee_transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_unit_id', sa.Integer(), nullable=True),
    sa.Column('to_unit_id', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.Enum('PROMOTION', 'DEMOTION', 'TRANSFER', name='transfertype'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_unit_id'], ['organization_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_unit_id'], ['organization_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfer_effective_date', 'employee_transfer', ['effective_date'], unique=False)
    op.create_index('idx_transfer_employee', 'employee_transfer', ['employee_id'], unique=False)
    op.create_table('user_employee_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_mapping_employee', 'user_employee_mapping', ['employee_id'], unique=False)
    op.create_index('idx_mapping_user', 'user_employee_mapping', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mapping_user', table_name='user_employee_mapping')
    op.drop_index('idx_mapping_employee', table_name='user_employee_mapping')
    op.drop_table('user_employee_mapping')
    op.drop_index('idx_transfer_employee', table_name='employee_transfer')
    op.drop_index('idx_transfer_effective_date', table_name='employee_transfer')
    op.drop_table('employee_transfer')
    op.drop_index('idx_secondary_unit', table_name='employee_secondary_unit')
    op.drop_index('idx_secondary_employee', table_name='employee_secondary_unit')
    op.drop_table('employee_secondary_unit')
    op.drop_index('idx_closure_descendant', table_name='org_unit_closure')
    op.drop_index('idx_closure_depth', table_name='org_unit_closure')
    op.drop_index('idx_closure_ancestor', table_name='org_unit_closure')
    op.drop_table('org_unit_closure')
    op.drop_index(op.f('ix_employee_primary_unit_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_employee_no'), table_name='employee')
    op.drop_index('idx_employee_unit_status', table_name='employee')
    op.drop_index('idx_employee_status', table_name='employee')
    op.drop_index('idx_employee_name', table_name='employee')
    op.drop_index('idx_employee_deleted', table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_organization_unit_parent_id'), table_name='organization_unit')
    op.drop_index(op.f('ix_organization_unit_code'), table_name='organization_unit')
    op.drop_index('idx_org_unit_status', table_name='organization_unit')
    op.drop_index('idx_org_unit_parent_level', table_name='organization_unit')
    op.drop_table('organization_unit')
    # ### end Alembic commands ###